In [1]:
!pip install torch numpy --quiet

In [2]:
import torch

In [3]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [12]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [13]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
# Compute derivatives
y.backward()

In [15]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [16]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [17]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [18]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [19]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [20]:
#Linear Regression

In [21]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [23]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [24]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [25]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.4368, -2.0593, -1.0982],
        [-0.8542,  0.7664,  0.5739]], requires_grad=True)
tensor([-0.2242,  0.1149], requires_grad=True)


In [26]:
def model(x):
    return x @ w.t() + b

In [27]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-153.5308,   13.7814],
        [-211.9755,   26.5509],
        [-301.8600,   61.7803],
        [ -84.8506,  -32.8290],
        [-244.6494,   54.9188]], grad_fn=<AddBackward0>)


In [28]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [29]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [30]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(46189.6094, grad_fn=<DivBackward0>)


In [31]:
# Compute gradients
loss.backward()

In [32]:
# Gradients for weights
print(w.grad)

tensor([[ 0.4368, -2.0593, -1.0982],
        [-0.8542,  0.7664,  0.5739]], requires_grad=True)
tensor([[-22691.5820, -26836.9160, -16091.8135],
        [ -5723.8188,  -5803.2080,  -3676.4475]])


In [33]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [34]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-153.5308,   13.7814],
        [-211.9755,   26.5509],
        [-301.8600,   61.7803],
        [ -84.8506,  -32.8290],
        [-244.6494,   54.9188]], grad_fn=<AddBackward0>)


In [35]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(46189.6094, grad_fn=<DivBackward0>)


In [36]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-22691.5820, -26836.9160, -16091.8135],
        [ -5723.8188,  -5803.2080,  -3676.4475]])
tensor([-275.5732,  -67.1595])


In [37]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [38]:
print(w)
print(b)

tensor([[ 0.6638, -1.7909, -0.9373],
        [-0.7970,  0.8245,  0.6106]], requires_grad=True)
tensor([-0.2214,  0.1155], requires_grad=True)


In [39]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(31855.5566, grad_fn=<DivBackward0>)


In [40]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [41]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(660.2444, grad_fn=<DivBackward0>)


In [42]:
# Predictions
preds

tensor([[ 68.7510,  68.9210],
        [ 86.0333,  98.3817],
        [ 91.3640, 140.3950],
        [ 88.2257,  28.6960],
        [ 69.3519, 120.0350]], grad_fn=<AddBackward0>)

In [43]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [44]:
import torch.nn as nn

In [45]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [46]:
from torch.utils.data import TensorDataset

In [47]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [48]:
from torch.utils.data import DataLoader

In [49]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [50]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [103., 119.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.]])


In [51]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1064,  0.2498,  0.2676],
        [ 0.0056,  0.0649, -0.5215]], requires_grad=True)
Parameter containing:
tensor([-0.2268, -0.4935], requires_grad=True)


In [52]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.1064,  0.2498,  0.2676],
         [ 0.0056,  0.0649, -0.5215]], requires_grad=True),
 Parameter containing:
 tensor([-0.2268, -0.4935], requires_grad=True)]

In [53]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 20.2450, -18.1645],
        [ 29.1937, -27.6537],
        [ 39.5033, -21.5614],
        [  9.5592, -16.4311],
        [ 35.1383, -30.3864],
        [ 20.2450, -18.1645],
        [ 29.1937, -27.6537],
        [ 39.5033, -21.5614],
        [  9.5592, -16.4311],
        [ 35.1383, -30.3864],
        [ 20.2450, -18.1645],
        [ 29.1937, -27.6537],
        [ 39.5033, -21.5614],
        [  9.5592, -16.4311],
        [ 35.1383, -30.3864]], grad_fn=<AddmmBackward0>)

In [54]:
# Import nn.functional
import torch.nn.functional as F

In [55]:
# Define loss function
loss_fn = F.mse_loss

In [56]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8842.7197, grad_fn=<MseLossBackward0>)


In [57]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [58]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [59]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 217.5561
Epoch [20/100], Loss: 102.2766
Epoch [30/100], Loss: 167.9443
Epoch [40/100], Loss: 174.9510
Epoch [50/100], Loss: 112.7788
Epoch [60/100], Loss: 77.3819
Epoch [70/100], Loss: 42.6351
Epoch [80/100], Loss: 43.1147
Epoch [90/100], Loss: 69.3258
Epoch [100/100], Loss: 45.7341


In [60]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.0395,  71.5443],
        [ 81.6474,  95.3588],
        [118.7574, 141.1927],
        [ 26.1113,  45.5266],
        [ 97.9526, 104.9689],
        [ 58.0395,  71.5443],
        [ 81.6474,  95.3588],
        [118.7574, 141.1927],
        [ 26.1113,  45.5266],
        [ 97.9526, 104.9689],
        [ 58.0395,  71.5443],
        [ 81.6474,  95.3588],
        [118.7574, 141.1927],
        [ 26.1113,  45.5266],
        [ 97.9526, 104.9689]], grad_fn=<AddmmBackward0>)

In [61]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])